server:
  port: 8443
#数据库配置
spring:
  #导入的pom文件
  application:
    name: agriculture
  #数据库驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/agriculture
    username: root
    password: 123456

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html




  redis:
    #host: 172.16.1.12
    #port: 8080
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-idle: 20


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.tyut.model
  global-config:
    banner: false
    db-config:
      id-type: INPUT
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
